export const mainTheme = {
  token: {},
  components: {
    Form: {
      colorError: "#F5382C",
    },
    Checkbox: {
      colorPrimary: "#FAA39E",
      colorPrimaryHover: "#FAA39E",
    },
    Select: {
      colorBgContainer: "rgba(0,0,0,0)",
      fontSize: 20,
      optionSelectedColor: "#FAFAFA",
      optionSelectedBg: "#F5382C",
      optionActiveBg: "#F5382C",
      optionActiveColor: "#FAFAFA",
      colorBorder: "#E6E7E6",
      colorBgElevated: "#FAFAFA",
      selectorBg: "#FAFAFA",
      colorText: "#222222",
      colorTextPlaceholder: "rgb(0, 0, 0,0.5)",
      // activeOutlineColor: "#FAA39E",
      // activeBorderColor: "#FAA39E",
      hoverBorderColor: "#FAA39E",
    },
    DatePicker: {
      fontSize: 20,
      colorBorder: "rgb(0, 0, 0,0.5)",
      colorTextPlaceholder: "rgb(0, 0, 0,0.5)",
    },
    Upload: {
      colorFillAlter: "rgba(0,0,0,0)",
      colorBorder: "#FAA39E",
      colorBorderHover: "#FAA39E",
      colorText: "#FAA39E",
    },
    Table: {
      headerBg: "#F8FAFC",
      colorBgContainer: "#FEFFFF",
      colorText: "#232323",
      borderColor: "#DFE1E3",
      headerColor: "#000000",
      fontSize: 18,
      // footerColor: "rgba(31, 41, 55, 0.88)",
      // marginXXS: 4,
      colorLinkActive: "rgb(107, 114, 128)",
      headerSplitColor: "rgb(0, 0, 0,0)",
    },
  },
};
